title: Autocratic Association of Autism
markdown: kramdown
collections:
  ledger:
    output: true
    permalink: /ledger/:name.html
defaults:
  - scope:
      path: ""
      type: ledger
    values:
      layout: ledger_issue
